from pymongo import MongoClient

# nos conectamos a la base local de docker
client = MongoClient('mongodb://superheroe_db:27017/')
db = client['super_db']
col = db['personajes']

# borramos todo lo que haya para no duplicar datos si lo corres dos veces
col.delete_many({})

personajes = [
    # --- MARVEL (20 pj) ---
    {"nombre": "Spider-Man", "nombreReal": "Peter Parker", "anioAparicion": 1962, "casa": "MARVEL", 
     "biografia": "Un joven de Queens que obtiene poderes arácnidos tras ser mordido por una araña radiactiva.", 
     "equipamiento": "Lanzatelarañas, sensores arácnidos", "imagenes": ["spider-man.png"]},
    {"nombre": "Iron Man", "nombreReal": "Tony Stark", "anioAparicion": 1963, "casa": "MARVEL", 
     "biografia": "Genio multimillonario que construye una armadura de alta tecnología para salvar su vida y proteger al mundo.", 
     "equipamiento": "Armaduras Mark, IA Jarvis/Friday", "imagenes": ["iron_man.png"]},
    {"nombre": "Captain America", "nombreReal": "Steve Rogers", "anioAparicion": 1941, "casa": "MARVEL", 
     "biografia": "Súper soldado de la Segunda Guerra Mundial, símbolo de libertad y justicia.", 
     "equipamiento": "Escudo de vibranium", "imagenes": ["captain_america.png"]},
    {"nombre": "Thor", "nombreReal": "Thor Odinson", "anioAparicion": 1962, "casa": "MARVEL", 
     "biografia": "Dios del Trueno de Asgard y miembro fundador de los Vengadores.", 
     "equipamiento": "Martillo Mjolnir, Stormbreaker", "imagenes": ["thor.png"]},
    {"nombre": "Hulk", "nombreReal": "Bruce Banner", "anioAparicion": 1962, "casa": "MARVEL", 
     "biografia": "Científico expuesto a radiación gamma que se transforma en un gigante verde cuando se enfurece.", 
     "equipamiento": "Fuerza bruta incalculable", "imagenes": ["hulk.png"]},
    {"nombre": "Black Widow", "nombreReal": "Natasha Romanoff", "anioAparicion": 1964, "casa": "MARVEL", 
     "biografia": "Ex espía de la KGB convertida en una de las agentes más letales de S.H.I.E.L.D.", 
     "equipamiento": "Aguijones de viuda, bastones eléctricos", "imagenes": ["black_widow.png"]},
    {"nombre": "Wolverine", "nombreReal": "James Logan Howlett", "anioAparicion": 1974, "casa": "MARVEL", 
     "biografia": "Mutante con sentidos animales y una capacidad de curación asombrosa.", 
     "equipamiento": "Garras de adamantium", "imagenes": ["wolverine.png"]},
    {"nombre": "Deadpool", "nombreReal": "Wade Wilson", "anioAparicion": 1991, "casa": "MARVEL", 
     "biografia": "Mercenario bocazas con factor de curación acelerado y un sentido del humor retorcido.", 
     "equipamiento": "Katanas, pistolas", "imagenes": ["deadpool.png"]},
    {"nombre": "Black Panther", "nombreReal": "T'Challa", "anioAparicion": 1966, "casa": "MARVEL", 
     "biografia": "Rey de Wakanda que utiliza un traje de vibranium para proteger a su nación.", 
     "equipamiento": "Traje de vibranium, garras", "imagenes": ["black_panther.png"]},
    {"nombre": "Doctor Strange", "nombreReal": "Stephen Strange", "anioAparicion": 1963, "casa": "MARVEL", 
     "biografia": "Hechicero Supremo que protege la Tierra contra amenazas mágicas y místicas.", 
     "equipamiento": "Capa de levitación, Ojo de Agamotto", "imagenes": ["doctor_strange.png"]},
    {"nombre": "Thanos", "nombreReal": "Thanos", "anioAparicion": 1973, "casa": "MARVEL", 
     "biografia": "El Titán Loco que busca recolectar las Gemas del Infinito para equilibrar el universo.", 
     "equipamiento": "Guantelete del Infinito", "imagenes": ["thanos.png"]},
    {"nombre": "Venom", "nombreReal": "Eddie Brock", "anioAparicion": 1988, "casa": "MARVEL", 
     "biografia": "Simbiote alienígena que se une a un humano para formar una criatura poderosa y caótica.", 
     "equipamiento": "Habilidades simbióticas", "imagenes": ["venom.png"]},
    {"nombre": "Daredevil", "nombreReal": "Matt Murdock", "anioAparicion": 1964, "casa": "MARVEL", 
     "biografia": "Abogado ciego de Hell's Kitchen con sentidos hiperdesarrollados.", 
     "equipamiento": "Bastones de combate", "imagenes": ["daredevil.png"]},
    {"nombre": "Magneto", "nombreReal": "Erik Lehnsherr", "anioAparicion": 1963, "casa": "MARVEL", 
     "biografia": "Poderoso mutante con la capacidad de controlar campos magnéticos.", 
     "equipamiento": "Casco protector mental", "imagenes": ["magneto.png"]},
    {"nombre": "Storm", "nombreReal": "Ororo Munroe", "anioAparicion": 1975, "casa": "MARVEL", 
     "biografia": "Mutante capaz de controlar el clima y las tormentas.", 
     "equipamiento": "Vuelo y control atmosférico", "imagenes": ["storm.png"]},
    {"nombre": "Loki", "nombreReal": "Loki Laufeyson", "anioAparicion": 1962, "casa": "MARVEL", 
     "biografia": "Dios de las mentiras y hermano adoptivo de Thor.", 
     "equipamiento": "Cetro, magia de ilusión", "imagenes": ["loki.png"]},
    {"nombre": "Star-Lord", "nombreReal": "Peter Quill", "anioAparicion": 1976, "casa": "MARVEL", 
     "biografia": "Líder de los Guardianes de la Galaxia, mitad humano y mitad celestial.", 
     "equipamiento": "Blásters elementales, botas jet", "imagenes": ["star_lord.png"]},
    {"nombre": "Groot", "nombreReal": "Groot", "anioAparicion": 1960, "casa": "MARVEL", 
     "biografia": "Criatura arbórea extraterrestre de gran fuerza y pocas palabras.", 
     "equipamiento": "Crecimiento de ramas, regeneración", "imagenes": ["groot.png"]},
    {"nombre": "Moon Knight", "nombreReal": "Marc Spector", "anioAparicion": 1975, "casa": "MARVEL", 
     "biografia": "Mercenario con trastorno de identidad disociativo, avatar del dios egipcio Khonshu.", 
     "equipamiento": "Dardos crecientes, bastón", "imagenes": ["moon_knight.png"]},
    {"nombre": "Captain Marvel", "nombreReal": "Carol Danvers", "anioAparicion": 1968, "casa": "MARVEL", 
     "biografia": "Piloto humana que obtuvo poderes cósmicos masivos tras un accidente.", 
     "equipamiento": "Energía cósmica", "imagenes": ["captain_marvel.png"]},

    # --- DC (20 pj) ---
    {"nombre": "Batman", "nombreReal": "Bruce Wayne", "anioAparicion": 1939, "casa": "DC", 
     "biografia": "Vigilante millonario que protege Gotham usando su intelecto y entrenamiento.", 
     "equipamiento": "Bati-cinturón, Batmóvil", "imagenes": ["batman.png"]},
    {"nombre": "Superman", "nombreReal": "Clark Kent", "anioAparicion": 1938, "casa": "DC", 
     "biografia": "Kryptoniano enviado a la Tierra con poderes divinos bajo el sol amarillo.", 
     "equipamiento": "Capa, traje kryptoniano", "imagenes": ["superman.png"]},
    {"nombre": "Wonder Woman", "nombreReal": "Diana Prince", "anioAparicion": 1941, "casa": "DC", 
     "biografia": "Princesa amazona guerrera y defensora de la paz mundial.", 
     "equipamiento": "Lazo de la verdad, brazaletes", "imagenes": ["wonder_woman.png"]},
    {"nombre": "The Flash", "nombreReal": "Barry Allen", "anioAparicion": 1956, "casa": "DC", 
     "biografia": "Científico forense que obtiene supervelocidad tras un accidente de laboratorio.", 
     "equipamiento": "Anillo del traje, Speed Force", "imagenes": ["the_flash.png"]},
    {"nombre": "Aquaman", "nombreReal": "Arthur Curry", "anioAparicion": 1941, "casa": "DC", 
     "biografia": "Rey de la Atlántida que protege los océanos y la superficie.", 
     "equipamiento": "Tridente de Neptuno", "imagenes": ["aquaman.png"]},
    {"nombre": "Green Lantern", "nombreReal": "Hal Jordan", "anioAparicion": 1959, "casa": "DC", 
     "biografia": "Piloto de pruebas reclutado por una fuerza policial intergaláctica.", 
     "equipamiento": "Anillo de poder verde", "imagenes": ["green_lantern.png"]},
    {"nombre": "Joker", "nombreReal": "Desconocido", "anioAparicion": 1940, "casa": "DC", 
     "biografia": "El archienemigo de Batman, un genio criminal psicópata y caótico.", 
     "equipamiento": "Gas de la risa, gadgets de broma", "imagenes": ["joker.png"]},
    {"nombre": "Harley Quinn", "nombreReal": "Harleen Quinzel", "anioAparicion": 1992, "casa": "DC", 
     "biografia": "Ex psiquiatra de Arkham que se unió al Joker antes de seguir su propio camino.", 
     "equipamiento": "Mazo gigante, bate de béisbol", "imagenes": ["harley_quinn.png"]},
    {"nombre": "Lex Luthor", "nombreReal": "Lex Luthor", "anioAparicion": 1940, "casa": "DC", 
     "biografia": "Multimillonario brillante que ve a Superman como una amenaza para la humanidad.", 
     "equipamiento": "Armadura de guerra, kryptonita", "imagenes": ["lex_luthor.png"]},
    {"nombre": "Cyborg", "nombreReal": "Victor Stone", "anioAparicion": 1980, "casa": "DC", 
     "biografia": "Atleta reconstruido con tecnología avanzada tras un accidente fatal.", 
     "equipamiento": "Cañón de sonido, interfaz digital", "imagenes": ["cyborg.png"]},
    {"nombre": "Shazam", "nombreReal": "Billy Batson", "anioAparicion": 1939, "casa": "DC", 
     "biografia": "Un niño que al decir 'Shazam' se transforma en un adulto con poderes mágicos.", 
     "equipamiento": "Poderes de los dioses", "imagenes": ["shazam.png"]},
    {"nombre": "Green Arrow", "nombreReal": "Oliver Queen", "anioAparicion": 1941, "casa": "DC", 
     "biografia": "Arquero experto que lucha por la justicia social en Star City.", 
     "equipamiento": "Arco y flechas trucadas", "imagenes": ["green_arrow.png"]},
    {"nombre": "Nightwing", "nombreReal": "Dick Grayson", "anioAparicion": 1984, "casa": "DC", 
     "biografia": "El primer Robin que creció y se convirtió en su propio héroe en Blüdhaven.", 
     "equipamiento": "Escrimas eléctricas", "imagenes": ["nightwing.png"]},
    {"nombre": "Catwoman", "nombreReal": "Selina Kyle", "anioAparicion": 1940, "casa": "DC", 
     "biografia": "Ladrona experta con un código moral complejo y relación con Batman.", 
     "equipamiento": "Látigo, garras", "imagenes": ["catwoman.png"]},
    {"nombre": "Black Adam", "nombreReal": "Teth-Adam", "anioAparicion": 1945, "casa": "DC", 
     "biografia": "Antiguo egipcio con los mismos poderes de Shazam pero con una visión brutal de la justicia.", 
     "equipamiento": "Vuelo y relámpagos mágicos", "imagenes": ["black_adam.png"]},
    {"nombre": "Deathstroke", "nombreReal": "Slade Wilson", "anioAparicion": 1980, "casa": "DC", 
     "biografia": "El mercenario y asesino más letal del mundo, con habilidades aumentadas.", 
     "equipamiento": "Espadas, arsenal militar", "imagenes": ["deathstroke.png"]},
    {"nombre": "Raven", "nombreReal": "Rachel Roth", "anioAparicion": 1980, "casa": "DC", 
     "biografia": "Hija de un demonio con poderosas habilidades empáticas y mágicas.", 
     "equipamiento": "Magia oscura", "imagenes": ["raven.png"]},
    {"nombre": "Beast Boy", "nombreReal": "Garfield Logan", "anioAparicion": 1965, "casa": "DC", 
     "biografia": "Mutante capaz de transformarse en cualquier animal que haya visto.", 
     "equipamiento": "Metamorfosis animal", "imagenes": ["beast_boy.png"]},
    {"nombre": "Robin", "nombreReal": "Damian Wayne", "anioAparicion": 2006, "casa": "DC", 
     "biografia": "Hijo de Batman entrenado por la Liga de Asesinos.", 
     "equipamiento": "Katana, bati-gadgets", "imagenes": ["robin.png"]},
    {"nombre": "Blue Beetle", "nombreReal": "Jaime Reyes", "anioAparicion": 2006, "casa": "DC", 
     "biografia": "Joven que se une a un escarabajo alienígena que le otorga una armadura poderosa.", 
     "equipamiento": "Armadura biotecnológica", "imagenes": ["blue_beetle.png"]}
]

# insertamos todo en la colección
col.insert_many(personajes)

print(f"Se cargaron {col.count_documents({})} personajes correctamente.")